create extension if not exists pgcrypto;

create type public.reading_status as enum ('TBR', 'Reading', 'Finished');
create type public.featured_content_type as enum ('quiz', 'book_list', 'article', 'recommendation');

create table public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  cover_image text,
  description text not null default '',
  genre text,
  publication_year integer,
  isbn text unique,
  created_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  profile_picture text,
  bio text not null default '',
  favorite_book_1 bigint references public.books(id) on delete set null,
  favorite_book_2 bigint references public.books(id) on delete set null,
  favorite_book_3 bigint references public.books(id) on delete set null,
  favorite_book_4 bigint references public.books(id) on delete set null,
  favorite_genres text[] not null default '{}',
  reading_goal integer not null default 0 check (reading_goal >= 0),
  current_streak integer not null default 0 check (current_streak >= 0),
  created_at timestamptz not null default now()
);

create table public.user_books (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  book_id bigint not null references public.books(id) on delete cascade,
  status public.reading_status not null,
  rating smallint check (rating between 1 and 5),
  review text,
  start_date date,
  finish_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, book_id)
);

create table public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(trim(content)) between 1 and 2000),
  book_id bigint references public.books(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(trim(content)) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table public.likes (
  user_id uuid not null references public.profiles(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

create table public.book_clubs (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 100),
  description text not null default '',
  book_id bigint not null references public.books(id) on delete restrict,
  creator_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.club_members (
  club_id bigint not null references public.book_clubs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (club_id, user_id)
);

create table public.club_messages (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.book_clubs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  message text not null check (char_length(trim(message)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table public.reading_challenges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  target_books integer not null check (target_books > 0),
  books_completed integer not null default 0 check (books_completed >= 0),
  year integer not null check (year between 2000 and 2200),
  unique (user_id, year)
);

create table public.badges (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null,
  icon text
);

create table public.user_badges (
  user_id uuid not null references public.profiles(id) on delete cascade,
  badge_id bigint not null references public.badges(id) on delete cascade,
  earned_at timestamptz not null default now(),
  primary key (user_id, badge_id)
);

create table public.featured_content (
  id bigint generated by default as identity primary key,
  title text not null,
  type public.featured_content_type not null,
  content jsonb not null default '{}',
  month smallint not null check (month between 1 and 12),
  year integer not null,
  created_at timestamptz not null default now()
);

create index user_books_user_status_idx on public.user_books(user_id, status);
create index posts_created_at_idx on public.posts(created_at desc);
create index comments_post_created_idx on public.comments(post_id, created_at);
create index club_messages_club_created_idx on public.club_messages(club_id, created_at);
create index featured_content_period_idx on public.featured_content(year, month);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger user_books_set_updated_at before update on public.user_books
for each row execute function public.set_updated_at();

create or replace function public.create_profile_for_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, name, email)
  values (new.id, coalesce(nullif(new.raw_user_meta_data ->> 'name', ''), split_part(new.email, '@', 1)), new.email);
  return new;
end;
$$;

create trigger create_profile_after_signup after insert on auth.users
for each row execute function public.create_profile_for_new_user();

create or replace function public.join_created_club()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.club_members (club_id, user_id) values (new.id, new.creator_id);
  return new;
end;
$$;

create trigger creator_joins_club after insert on public.book_clubs
for each row execute function public.join_created_club();

alter table public.books enable row level security;
alter table public.profiles enable row level security;
alter table public.user_books enable row level security;
alter table public.posts enable row level security;
alter table public.comments enable row level security;
alter table public.likes enable row level security;
alter table public.book_clubs enable row level security;
alter table public.club_members enable row level security;
alter table public.club_messages enable row level security;
alter table public.reading_challenges enable row level security;
alter table public.badges enable row level security;
alter table public.user_badges enable row level security;
alter table public.featured_content enable row level security;

create policy "Students read books" on public.books for select to authenticated using (true);
create policy "Students add books" on public.books for insert to authenticated with check (true);
create policy "Students read profiles" on public.profiles for select to authenticated using (true);
create policy "Students update own profile" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "Students read shelves" on public.user_books for select to authenticated using (true);
create policy "Students add own shelf books" on public.user_books for insert to authenticated with check (user_id = auth.uid());
create policy "Students update own shelf books" on public.user_books for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Students delete own shelf books" on public.user_books for delete to authenticated using (user_id = auth.uid());
create policy "Students read posts" on public.posts for select to authenticated using (true);
create policy "Students create own posts" on public.posts for insert to authenticated with check (user_id = auth.uid());
create policy "Students update own posts" on public.posts for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Students delete own posts" on public.posts for delete to authenticated using (user_id = auth.uid());
create policy "Students read comments" on public.comments for select to authenticated using (true);
create policy "Students create own comments" on public.comments for insert to authenticated with check (user_id = auth.uid());
create policy "Students delete own comments" on public.comments for delete to authenticated using (user_id = auth.uid());
create policy "Students read likes" on public.likes for select to authenticated using (true);
create policy "Students create own likes" on public.likes for insert to authenticated with check (user_id = auth.uid());
create policy "Students delete own likes" on public.likes for delete to authenticated using (user_id = auth.uid());
create policy "Students read clubs" on public.book_clubs for select to authenticated using (true);
create policy "Students create clubs" on public.book_clubs for insert to authenticated with check (creator_id = auth.uid());
create policy "Creators update clubs" on public.book_clubs for update to authenticated using (creator_id = auth.uid()) with check (creator_id = auth.uid());
create policy "Creators delete clubs" on public.book_clubs for delete to authenticated using (creator_id = auth.uid());
create policy "Students read memberships" on public.club_members for select to authenticated using (true);
create policy "Students join clubs" on public.club_members for insert to authenticated with check (user_id = auth.uid());
create policy "Students leave clubs" on public.club_members for delete to authenticated using (user_id = auth.uid());
create policy "Members read club messages" on public.club_messages for select to authenticated using (
  exists (select 1 from public.club_members where club_id = club_messages.club_id and user_id = auth.uid())
);
create policy "Members send club messages" on public.club_messages for insert to authenticated with check (
  user_id = auth.uid() and exists (select 1 from public.club_members where club_id = club_messages.club_id and user_id = auth.uid())
);
create policy "Students delete own messages" on public.club_messages for delete to authenticated using (user_id = auth.uid());
create policy "Students read challenges" on public.reading_challenges for select to authenticated using (true);
create policy "Students create own challenges" on public.reading_challenges for insert to authenticated with check (user_id = auth.uid());
create policy "Students update own challenges" on public.reading_challenges for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Students read badges" on public.badges for select to authenticated using (true);
create policy "Students read earned badges" on public.user_badges for select to authenticated using (true);
create policy "Students read featured content" on public.featured_content for select to authenticated using (true);

insert into public.badges (name, description, icon) values
  ('First Book', 'Finish your first book.', '📖'),
  ('10 Books Read', 'Finish ten books.', '🔟'),
  ('100 Day Streak', 'Read for one hundred days in a row.', '🔥'),
  ('Review Writer', 'Publish your first review.', '✍️');
