alter table public.book_clubs
add column if not exists last_activity_at timestamptz not null default now(),
add column if not exists archived_at timestamptz,
add column if not exists archived_reason text;

update public.book_clubs
set last_activity_at = coalesce(updated_at, created_at, now())
where last_activity_at is null;

create table if not exists public.club_activity_events (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.book_clubs(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  event_type text not null check (
    event_type in ('created', 'joined', 'visited_room', 'posted_message', 'updated_schedule')
  ),
  created_at timestamptz not null default now()
);

create index if not exists club_activity_events_club_created_idx
on public.club_activity_events(club_id, created_at desc);

create index if not exists club_activity_events_user_created_idx
on public.club_activity_events(user_id, created_at desc);

create index if not exists book_clubs_active_activity_idx
on public.book_clubs(archived_at, last_activity_at desc);

alter table public.club_activity_events enable row level security;

drop policy if exists "Members create club activity events"
on public.club_activity_events;

create policy "Members create club activity events"
on public.club_activity_events
for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.club_members
    where club_members.club_id = club_activity_events.club_id
      and club_members.user_id = auth.uid()
  )
);

drop policy if exists "Members read club activity events"
on public.club_activity_events;

create policy "Members read club activity events"
on public.club_activity_events
for select
to authenticated
using (
  exists (
    select 1
    from public.club_members
    where club_members.club_id = club_activity_events.club_id
      and club_members.user_id = auth.uid()
  )
);

create or replace function public.record_club_activity(
  target_club_id bigint,
  target_user_id uuid,
  target_event_type text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if target_club_id is null then
    raise exception 'The club ID is missing.';
  end if;

  if target_user_id is null then
    raise exception 'The user ID is missing.';
  end if;

  if target_event_type not in (
    'created',
    'joined',
    'visited_room',
    'posted_message',
    'updated_schedule'
  ) then
    raise exception 'Unknown club activity event.';
  end if;

  if not exists (
    select 1
    from public.club_members
    where club_members.club_id = target_club_id
      and club_members.user_id = target_user_id
  ) then
    raise exception 'Only club members can record club activity.';
  end if;

  insert into public.club_activity_events (
    club_id,
    user_id,
    event_type
  )
  values (
    target_club_id,
    target_user_id,
    target_event_type
  );

  update public.book_clubs
  set
    last_activity_at = now(),
    updated_at = now()
  where id = target_club_id
    and archived_at is null;
end;
$$;

create or replace function public.track_joined_club_activity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.club_activity_events (
    club_id,
    user_id,
    event_type
  )
  values (
    new.club_id,
    new.user_id,
    'joined'
  );

  update public.book_clubs
  set
    last_activity_at = now(),
    updated_at = now()
  where id = new.club_id
    and archived_at is null;

  return new;
end;
$$;

drop trigger if exists track_joined_club_activity_after_insert
on public.club_members;

create trigger track_joined_club_activity_after_insert
after insert on public.club_members
for each row execute function public.track_joined_club_activity();

do $$
begin
  if to_regclass('public.club_posts') is not null then
    execute $sql$
      create or replace function public.track_club_post_activity()
      returns trigger
      language plpgsql
      security definer
      set search_path = ''
      as $function$
      begin
        insert into public.club_activity_events (
          club_id,
          user_id,
          event_type
        )
        values (
          new.club_id,
          new.user_id,
          'posted_message'
        );

        update public.book_clubs
        set
          last_activity_at = now(),
          updated_at = now()
        where id = new.club_id
          and archived_at is null;

        return new;
      end;
      $function$;
    $sql$;

    execute $sql$
      drop trigger if exists track_club_post_activity_after_insert
      on public.club_posts;
    $sql$;

    execute $sql$
      create trigger track_club_post_activity_after_insert
      after insert on public.club_posts
      for each row execute function public.track_club_post_activity();
    $sql$;
  end if;
end;
$$;

create or replace function public.archive_inactive_book_clubs(
  inactive_days integer default 7
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  archived_count integer;
begin
  update public.book_clubs
  set
    archived_at = now(),
    archived_reason = 'inactive_for_' || inactive_days::text || '_days',
    updated_at = now()
  where archived_at is null
    and coalesce(last_activity_at, created_at, now()) <
      now() - make_interval(days => inactive_days);

  get diagnostics archived_count = row_count;

  return archived_count;
end;
$$;

grant execute on function public.record_club_activity(bigint, uuid, text)
to authenticated;

grant execute on function public.archive_inactive_book_clubs(integer)
to authenticated;
