create table if not exists public.book_moderators (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.books
add column if not exists language text,
add column if not exists publisher text,
add column if not exists publication_year integer;

create table if not exists public.book_submissions (
  id uuid primary key default gen_random_uuid(),
  submitted_by uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  author text not null,
  language text not null,
  isbn text,
  publisher text,
  publication_year integer,
  description text,
  cover_url text,
  status text not null default 'pending',
  approved_book_id bigint references public.books(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint book_submissions_status_check
    check (status in ('pending', 'approved', 'rejected'))
);

create table if not exists public.book_submission_votes (
  id bigint generated by default as identity primary key,
  submission_id uuid not null references public.book_submissions(id) on delete cascade,
  moderator_id uuid not null references public.profiles(id) on delete cascade,
  decision text not null,
  comment text,
  created_at timestamptz not null default now(),
  constraint book_submission_votes_decision_check
    check (decision in ('approve', 'reject')),
  constraint book_submission_votes_submission_moderator_unique
    unique (submission_id, moderator_id)
);

alter table public.book_moderators enable row level security;
alter table public.book_submissions enable row level security;
alter table public.book_submission_votes enable row level security;

create or replace function public.is_book_moderator()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select auth.uid() is not null
    and exists (
      select 1
      from public.book_moderators
      where book_moderators.user_id = auth.uid()
    );
$$;

drop policy if exists "Users read own book moderator membership"
on public.book_moderators;

create policy "Users read own book moderator membership"
on public.book_moderators
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users create own book submissions"
on public.book_submissions;

create policy "Users create own book submissions"
on public.book_submissions
for insert
to authenticated
with check (
  submitted_by = auth.uid()
  and status = 'pending'
  and approved_book_id is null
);

drop policy if exists "Users read own book submissions"
on public.book_submissions;

create policy "Users read own book submissions"
on public.book_submissions
for select
to authenticated
using (submitted_by = auth.uid());

drop policy if exists "Book moderators read submissions"
on public.book_submissions;

create policy "Book moderators read submissions"
on public.book_submissions
for select
to authenticated
using (public.is_book_moderator());

drop policy if exists "Book moderators read submission votes"
on public.book_submission_votes;

create policy "Book moderators read submission votes"
on public.book_submission_votes
for select
to authenticated
using (public.is_book_moderator());

drop policy if exists "Authenticated users can add books"
on public.books;

create policy "Authenticated users can add books"
on public.books
for insert
to authenticated
with check (
  source in ('google_books', 'open_library', 'isbn_work')
);

create or replace function public.moderate_book_submission(
  p_submission_id uuid,
  p_decision text,
  p_comment text default null
)
returns public.book_submissions
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_moderator_id uuid;
  target_submission public.book_submissions%rowtype;
  approval_count integer;
  rejection_count integer;
  resolved_book_id bigint;
  normalized_isbn text;
begin
  current_moderator_id := auth.uid();

  if current_moderator_id is null then
    raise exception 'You must be logged in to moderate book submissions.';
  end if;

  if not exists (
    select 1
    from public.book_moderators
    where book_moderators.user_id = current_moderator_id
  ) then
    raise exception 'Only book moderators can moderate book submissions.';
  end if;

  if p_decision is null
    or p_decision not in ('approve', 'reject')
  then
    raise exception 'Moderation decision must be approve or reject.';
  end if;

  select *
  into target_submission
  from public.book_submissions
  where id = p_submission_id
  for update;

  if not found then
    raise exception 'Book submission not found.';
  end if;

  if target_submission.status <> 'pending' then
    raise exception 'Book submission has already been resolved.';
  end if;

  begin
    insert into public.book_submission_votes (
      submission_id,
      moderator_id,
      decision,
      comment
    )
    values (
      p_submission_id,
      current_moderator_id,
      p_decision,
      nullif(btrim(coalesce(p_comment, '')), '')
    );
  exception
    when unique_violation then
      raise exception 'You have already voted on this book submission.';
  end;

  select
    count(*) filter (where decision = 'approve'),
    count(*) filter (where decision = 'reject')
  into approval_count, rejection_count
  from public.book_submission_votes
  where submission_id = p_submission_id;

  if approval_count >= 2 then
    normalized_isbn := nullif(
      upper(regexp_replace(
        coalesce(target_submission.isbn, ''),
        '[^0-9Xx]',
        '',
        'g'
      )),
      ''
    );

    if normalized_isbn is not null then
      select books.id
      into resolved_book_id
      from public.books
      where upper(regexp_replace(
        coalesce(books.isbn, ''),
        '[^0-9Xx]',
        '',
        'g'
      )) = normalized_isbn
      limit 1;
    end if;

    if resolved_book_id is null then
      begin
        insert into public.books (
          title,
          author,
          isbn,
          language,
          publisher,
          publication_year,
          description,
          cover_url,
          source,
          external_id
        )
        values (
          target_submission.title,
          target_submission.author,
          normalized_isbn,
          target_submission.language,
          target_submission.publisher,
          target_submission.publication_year,
          target_submission.description,
          target_submission.cover_url,
          'community',
          null
        )
        returning id into resolved_book_id;
      exception
        when unique_violation then
          if normalized_isbn is null then
            raise;
          end if;

          select books.id
          into resolved_book_id
          from public.books
          where upper(regexp_replace(
            coalesce(books.isbn, ''),
            '[^0-9Xx]',
            '',
            'g'
          )) = normalized_isbn
          limit 1;

          if resolved_book_id is null then
            raise;
          end if;
      end;
    end if;

    update public.book_submissions
    set
      status = 'approved',
      approved_book_id = resolved_book_id,
      updated_at = now()
    where id = p_submission_id
    returning * into target_submission;
  elsif rejection_count >= 2 then
    update public.book_submissions
    set
      status = 'rejected',
      approved_book_id = null,
      updated_at = now()
    where id = p_submission_id
    returning * into target_submission;
  end if;

  return target_submission;
end;
$$;

revoke execute on function public.is_book_moderator()
from public;

grant execute on function public.is_book_moderator()
to authenticated;

revoke execute on function public.moderate_book_submission(uuid, text, text)
from public;

grant execute on function public.moderate_book_submission(uuid, text, text)
to authenticated;
