create table if not exists public.club_message_moderation_reports (
  id bigint generated by default as identity primary key,
  club_id bigint not null references public.book_clubs(id) on delete cascade,
  post_id bigint not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  original_message text not null default '',
  filtered_message text not null default '',
  matched_terms text[] not null default '{}',
  severity text not null default 'low' check (severity in ('low', 'medium', 'high', 'repeat')),
  strike_count integer not null default 1 check (strike_count > 0),
  status text not null default 'open' check (status in ('open', 'reviewed', 'dismissed')),
  created_at timestamptz not null default now()
);

alter table public.club_message_moderation_reports
drop constraint if exists club_message_moderation_reports_post_fk;

do $$
begin
  if to_regclass('public.club_posts') is not null then
    alter table public.club_message_moderation_reports
    add constraint club_message_moderation_reports_post_fk
    foreign key (post_id)
    references public.club_posts(id)
    on delete cascade
    not valid;

    alter table public.club_message_moderation_reports
    validate constraint club_message_moderation_reports_post_fk;
  end if;
end;
$$;

create index if not exists club_moderation_reports_status_created_idx
on public.club_message_moderation_reports(status, created_at desc);

create index if not exists club_moderation_reports_user_created_idx
on public.club_message_moderation_reports(user_id, created_at desc);

alter table public.club_message_moderation_reports enable row level security;

drop policy if exists "Members create club moderation reports"
on public.club_message_moderation_reports;

create policy "Members create club moderation reports"
on public.club_message_moderation_reports
for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.club_members
    where club_members.club_id = club_message_moderation_reports.club_id
      and club_members.user_id = auth.uid()
  )
);
