create table if not exists public.book_moderation_assessments (
  id uuid primary key default gen_random_uuid(),
  book_id bigint references public.books(id) on delete set null,
  source text not null,
  external_id text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'review_required', 'blocked', 'error')),
  confidence double precision not null default 0
    check (confidence >= 0 and confidence <= 1),
  evidence_quality text not null default 'insufficient'
    check (evidence_quality in ('high', 'medium', 'low', 'insufficient')),
  risk_scores jsonb not null default '{}'::jsonb,
  flags text[] not null default '{}',
  summary text not null default '',
  evidence jsonb not null default '{}'::jsonb,
  policy_version text not null,
  model_version text not null,
  manually_reviewed boolean not null default false,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint book_moderation_identity_not_blank check (
    btrim(source) <> '' and btrim(external_id) <> '' and btrim(policy_version) <> ''
  ),
  constraint book_moderation_manual_review_fields check (
    (not manually_reviewed and reviewed_by is null and reviewed_at is null)
    or (manually_reviewed and reviewed_by is not null and reviewed_at is not null)
  )
);

create unique index if not exists book_moderation_identity_policy_unique
on public.book_moderation_assessments(source, external_id, policy_version);

create index if not exists book_moderation_queue_idx
on public.book_moderation_assessments(status, manually_reviewed, updated_at desc);

create index if not exists book_moderation_book_idx
on public.book_moderation_assessments(book_id)
where book_id is not null;

create table if not exists public.book_moderation_events (
  id bigint generated by default as identity primary key,
  assessment_id uuid not null
    references public.book_moderation_assessments(id) on delete cascade,
  event_type text not null check (
    event_type in (
      'ai_assessed', 'human_approved', 'human_blocked',
      'returned_to_review', 'policy_reassessment', 'evidence_updated'
    )
  ),
  actor_id uuid references auth.users(id) on delete set null,
  previous_status text,
  next_status text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists book_moderation_events_assessment_idx
on public.book_moderation_events(assessment_id, created_at desc);

alter table public.book_moderation_assessments enable row level security;
alter table public.book_moderation_events enable row level security;

drop policy if exists "Admins read book moderation assessments"
on public.book_moderation_assessments;
create policy "Admins read book moderation assessments"
on public.book_moderation_assessments for select to authenticated
using (public.is_admin());

drop policy if exists "Admins read book moderation events"
on public.book_moderation_events;
create policy "Admins read book moderation events"
on public.book_moderation_events for select to authenticated
using (public.is_admin());

revoke all on table public.book_moderation_assessments from anon, authenticated;
revoke all on table public.book_moderation_events from anon, authenticated;
grant select on table public.book_moderation_assessments to authenticated;
grant select on table public.book_moderation_events to authenticated;

create or replace function public.review_book_moderation_assessment(
  p_assessment_id uuid,
  p_decision text
)
returns public.book_moderation_assessments
language plpgsql
security definer
set search_path = ''
as $$
declare
  target public.book_moderation_assessments%rowtype;
  next_status text;
  next_manual boolean;
begin
  if not public.is_admin() then
    raise exception 'Only admins can review book assessments.';
  end if;

  if p_decision = 'approve' then
    next_status := 'approved';
    next_manual := true;
  elsif p_decision = 'block' then
    next_status := 'blocked';
    next_manual := true;
  elsif p_decision = 'review_required' then
    next_status := 'review_required';
    next_manual := false;
  else
    raise exception 'Decision must be approve, block, or review_required.';
  end if;

  select * into target
  from public.book_moderation_assessments
  where id = p_assessment_id
  for update;

  if not found then raise exception 'Book assessment not found.'; end if;

  insert into public.book_moderation_events (
    assessment_id, event_type, actor_id, previous_status, next_status
  ) values (
    target.id,
    case p_decision
      when 'approve' then 'human_approved'
      when 'block' then 'human_blocked'
      else 'returned_to_review'
    end,
    auth.uid(), target.status, next_status
  );

  update public.book_moderation_assessments
  set status = next_status,
      manually_reviewed = next_manual,
      reviewed_by = case when next_manual then auth.uid() else null end,
      reviewed_at = case when next_manual then now() else null end,
      updated_at = now()
  where id = target.id
  returning * into target;

  return target;
end;
$$;

revoke all on function public.review_book_moderation_assessment(uuid, text) from public;
grant execute on function public.review_book_moderation_assessment(uuid, text) to authenticated;
