export const eventsEn = {
  live: "Live for everyone", adminPreview: "Admin preview · Events are hidden", hidden: "Admins only", publishLabel: "Publish Events", publishHelp: "Only owners can switch Events and its navigation link on or off for everyone.", ownerOnly: "Only an owner can change whether Events is live.", savingVisibility: "Saving…", visibilityError: "Could not change visibility. Please try again.", accessError: "This page is unavailable right now. Please try again.",
  title: "Events", intro: "Around LitShelf", subtitle: "Books bring us together. Here’s what’s happening, what’s next, and what we’re looking back on.",
  open: "Open now", soon: "Coming soon", recap: "Recap", back: "← All events", contribute: "Recommend a book", explore: "Meet the Reading Circle", read: "Visit the recap", book: "Find the book", circles: "Explore Circles", pendingRecap: "The story is being written", pendingCopy: "The festival has taken place. Our team is preparing the written recap and photos; they’ll appear here once ready.",
  separate: "This is a school library display activity, separate from the Gen Z Reading Festival.", formTitle: "Put your recommendation on the shelf", formIntro: "Choose a book from LitShelf, then add your photo, a favourite quote, and a short recommendation.",
  student: "Submitting as", profileError: "We couldn’t load your profile. Please try again.", signIn: "Sign in to contribute", privacy: "Your submission and photo will be available to LitShelf admins for review and preparation of the physical school library display. They won’t appear publicly on Events.",
  search: "Choose your book", searchHint: "Search LitShelf’s catalog by title, author, or ISBN.", noBooks: "No matching catalog books. Try another title, author, or ISBN, or find and add the book through Discover first.", discover: "Open Discover", selected: "Selected book", change: "Change book", photo: "Your photo", photoHelp: "Choose a clear photo of yourself. JPG, PNG or WebP, up to 5 MB.", photoError: "Choose a JPG, PNG or WebP image up to 5 MB.", quote: "A quote from the book", reason: "Why do you recommend it?", submit: "Submit recommendation", sending: "Uploading photo and submitting…", failed: "We couldn’t save your recommendation. Your form is still here; please try again.", success: "Your recommendation is in!", successHelp: "Thank you for helping shape the library display. LitShelf admins can now review your book, photo, quote and recommendation.", received: "You’ve already submitted a recommendation for this display.", loadError: "We couldn’t load submissions. Please try again.", review: "Library display", empty: "No submissions yet.", pending: "To review", reviewed: "Reviewed", mark: "Mark reviewed", reopen: "Return to review", photoOpen: "Open original photo", refresh: "Refresh", next: "Next page", previous: "Previous page", saved: "Review status saved.", photoFailed: "Couldn’t open the photo. Try again.", required: "Choose a book and photo, and complete both text fields.", checking: "Loading your submission…"
};
export const eventsZh = {
  live: "已公开", adminPreview: "管理员预览 · 活动尚未公开", hidden: "仅管理员可见", publishLabel: "公开活动页面", publishHelp: "只有所有者可以向所有人公开或隐藏活动页面及其导航入口。", ownerOnly: "只有所有者可以更改活动页面的公开状态。", savingVisibility: "正在保存…", visibilityError: "无法更改公开状态，请重试。", accessError: "此页面暂时不可用，请重试。",
  title: "活动", intro: "LitShelf 校园动态", subtitle: "以书相聚。看看正在进行的活动、即将开启的计划，以及值得回味的校园时光。",
  open: "正在征集", soon: "即将开启", recap: "活动回顾", back: "← 全部活动", contribute: "推荐一本书", explore: "了解共读计划", read: "查看回顾", book: "查找这本书", circles: "探索共读圈", pendingRecap: "故事正在整理中", pendingCopy: "阅读节已结束。团队正在整理回顾文章和照片，完成后将在这里发布。",
  separate: "这是学校图书馆的好书推荐展活动，与 Gen Z 阅读节无关。", formTitle: "让你的推荐登上书架", formIntro: "从 LitShelf 选择一本书，再添加你的照片、喜爱的书中摘录和简短推荐理由。",
  student: "提交者", profileError: "无法加载个人资料，请重试。", signIn: "登录并参与", privacy: "你的投稿和照片仅供 LitShelf 管理员审核并制作学校图书馆的实体展示，不会在活动页面公开。",
  search: "选择书籍", searchHint: "按书名、作者或 ISBN 搜索 LitShelf 书库。", noBooks: "书库中暂无匹配结果。请尝试其他书名、作者或 ISBN，或先通过发现页面查找并添加书籍。", discover: "前往发现", selected: "已选书籍", change: "更换书籍", photo: "你的照片", photoHelp: "请选择一张清晰的本人照片。支持 JPG、PNG 或 WebP，最大 5 MB。", photoError: "请选择不超过 5 MB 的 JPG、PNG 或 WebP 图片。", quote: "书中摘录", reason: "你为什么推荐这本书？", submit: "提交推荐", sending: "正在上传照片并提交…", failed: "推荐未能保存。表单内容已保留，请重试。", success: "推荐已收到！", successHelp: "感谢你参与图书馆好书推荐展。LitShelf 管理员现在可以查看你的书籍、照片、摘录与推荐理由。", received: "你已经为本次推荐展提交过推荐。", loadError: "无法加载投稿，请重试。", review: "图书馆推荐展", empty: "暂无投稿。", pending: "待审核", reviewed: "已审核", mark: "标记为已审核", reopen: "恢复为待审核", photoOpen: "打开原始照片", refresh: "刷新", next: "下一页", previous: "上一页", saved: "审核状态已保存。", photoFailed: "无法打开照片，请重试。", required: "请选择书籍和照片，并填写两项文字内容。", checking: "正在加载你的投稿…"
};
